/**
 * @packageDocumentation
 * This module stores static literals for terms & conditions and privacy policy.
 * These literals have been abstracted due to their size and complexity.
 */

/*************/
/** Objects **/
/*************/

/**
 * Stores the privacy policy translations.
 */
const privacy = {
  en: {
    title: 'Privacy policy',
    1: 'Recogida y tratamiento de datos de carácter personal \n\n Los datos de carácter personal son los que pueden ser utilizados para identificar a una persona o ponerse en contacto con ella. \n\n INGENIOS TELEMATICOS puede solicitar datos personales de usuarios al acceder a aplicaciones de la empresa o de otras empresas afiliadas, así como la posibilidad de que entre estas empresas puedan compartir esos datos para mejorar los productos y servicios ofrecidos. Si no se facilitan esos datos personales, en muchos casos no podremos ofrecer los productos o servicios solicitados. \n\n Estos son algunos ejemplos de las categorías de datos de carácter personal que INGENIOS TELEMATICOS puede recoger y la finalidad para los que puede llevar a cabo el tratamiento de estos datos. ¿Qué datos de carácter personal se pueden recopilar? \n\n - Al crear un ID, solicitar un crédito comercial, comprar un producto, descargar una actualización de software, se recopilan diferentes datos, como nombre, dirección postal, número de teléfono, dirección de correo electrónico o los datos de la tarjeta de crédito. \n\n - Cuando se comparten contenidos con familiares y amigos o se invita a otras personas a participar en los servicios o foros, pueden recogerse los datos que facilitamos sobre esas personas, como su nombre, domicilio, correo electrónico y número de teléfono. Se utilizarán dichos datos para completar sus pedidos, mostrarle el producto o servicio correspondiente o para combatir el fraude.\n',
    2: 'Propósito del tratamiento de datos de carácter personal \n\n INGENIOS TELEMATICOS podrá utilizar los datos personales recabados para: \n\n - Los datos de carácter personal recopilados permiten mantenerle informado acerca de los últimos productos, las actualizaciones de software disponibles y los próximos eventos. \n\n - También se utilizan los datos de carácter personal como ayuda para elaborar, perfeccionar, gestionar, proporcionar y mejorar los productos, servicios, contenidos y publicidad, y con el propósito de evitar pérdidas y fraudes. \n\n - Pueden utilizarse los datos de carácter personal para comprobar la identidad, colaborar en la identificación de usuarios y decidir los servicios apropiados. \n\n - También se utilizan esos datos de carácter personal con propósitos internos, incluyendo auditorías, análisis de datos y sondeos, para mejorar los productos, servicios y comunicaciones a clientes. \n\n - Si participa en un sorteo, un concurso o una promoción, pueden usarse los datos proporcionados para administrar estos programas. \n\n - Recopilación y tratamiento de datos de carácter no personal.',
  },
  es: {
    title: 'Política de privacidad',
    1: 'Recogida y tratamiento de datos de carácter personal \n\n Los datos de carácter personal son los que pueden ser utilizados para identificar a una persona o ponerse en contacto con ella. \n\n INGENIOS TELEMATICOS puede solicitar datos personales de usuarios al acceder a aplicaciones de la empresa o de otras empresas afiliadas, así como la posibilidad de que entre estas empresas puedan compartir esos datos para mejorar los productos y servicios ofrecidos. Si no se facilitan esos datos personales, en muchos casos no podremos ofrecer los productos o servicios solicitados. \n\n Estos son algunos ejemplos de las categorías de datos de carácter personal que INGENIOS TELEMATICOS puede recoger y la finalidad para los que puede llevar a cabo el tratamiento de estos datos. ¿Qué datos de carácter personal se pueden recopilar? \n\n - Al crear un ID, solicitar un crédito comercial, comprar un producto, descargar una actualización de software, se recopilan diferentes datos, como nombre, dirección postal, número de teléfono, dirección de correo electrónico o los datos de la tarjeta de crédito. \n\n - Cuando se comparten contenidos con familiares y amigos o se invita a otras personas a participar en los servicios o foros, pueden recogerse los datos que facilitamos sobre esas personas, como su nombre, domicilio, correo electrónico y número de teléfono. Se utilizarán dichos datos para completar sus pedidos, mostrarle el producto o servicio correspondiente o para combatir el fraude.\n',
    2: 'Propósito del tratamiento de datos de carácter personal \n\n INGENIOS TELEMATICOS podrá utilizar los datos personales recabados para: \n\n - Los datos de carácter personal recopilados permiten mantenerle informado acerca de los últimos productos, las actualizaciones de software disponibles y los próximos eventos. \n\n - También se utilizan los datos de carácter personal como ayuda para elaborar, perfeccionar, gestionar, proporcionar y mejorar los productos, servicios, contenidos y publicidad, y con el propósito de evitar pérdidas y fraudes. \n\n - Pueden utilizarse los datos de carácter personal para comprobar la identidad, colaborar en la identificación de usuarios y decidir los servicios apropiados. \n\n - También se utilizan esos datos de carácter personal con propósitos internos, incluyendo auditorías, análisis de datos y sondeos, para mejorar los productos, servicios y comunicaciones a clientes. \n\n - Si participa en un sorteo, un concurso o una promoción, pueden usarse los datos proporcionados para administrar estos programas. \n\n - Recopilación y tratamiento de datos de carácter no personal. \n\n INGENIOS TELEMATICOS también recopilará datos de un modo que, por sí mismos, no pueden ser asociados directamente a una persona determinada. Estos datos de carácter no personal se pueden recopilar, tratar, transferir y publicar con cualquier intención. Estos son algunos ejemplos de las clases de datos de carácter no personal que INGENIOS TELEMATICOS puede recopilar y los fines para los que se realiza su tratamiento: \n\n - Datos tales como registro de actividad, para prestar el servicio de vigilancia de personas mayores. \n\n Si juntamos datos de carácter no personal con datos personales, los datos mezclados serán tratados como datos personales mientras sigan estando combinados.\n',
    3: 'Proveedores de servicios \n\n INGENIOS TELEMATICOS compartirá datos de carácter personal con empresas que se ocupan, entre otras actividades, de prestar servicios de tratamiento de datos, conceder créditos, tramitar pedidos de clientes, presentar sus productos, mejorar datos de clientes, suministrar servicios de atención al cliente, evaluar su interés en productos y servicios y realizar investigaciones sobre clientes o su grado de satisfacción.\n',
    4: 'Otros terceros \n\n Es posible que INGENIOS TELEMATICOS divulgue datos de carácter personal por mandato legal, en el marco de un proceso judicial o por petición de una autoridad pública, tanto dentro como fuera de su país de residencia. Igualmente se puede publicar información personal si es necesaria o conveniente por motivos de seguridad nacional, para acatar la legislación vigente o por otras razones relevantes de orden público. \n\n - Protección de datos de carácter personal \n\n INGENIOS TELEMATICOS garantizará la protección de los datos personales mediante cifrado durante el tránsito y, los alojados en instalaciones, con medidas de seguridad físicas. \n\n Al usar ciertos productos, servicios o aplicaciones o al publicar opiniones en foros, salas de chat o redes sociales, el contenido y los datos de carácter personal que se comparta serán visible para otros usuarios, que tendrán la posibilidad de leerlos, compilarlos o usarlos. Usted será responsable de los datos de carácter personal que distribuya o proporcione en estos casos.\n',
    5: 'Integridad y conservación de datos de carácter personal \n\n INGENIOS TELEMATICOS garantizará la exactitud y la calidad de los datos personales, se conservarán durante el tiempo necesario para cumplir los fines para los que fueron recabados, salvo que la ley exija conservarlos durante más tiempo.\n',
    6: 'Acceso a los datos de carácter personal \n\n Respecto a los datos de carácter personal que conservamos, INGENIOS TELEMATICOS le ofrece acceso a ellos para cualquier fin, incluyendo las solicitudes de rectificación en caso de que sean incorrectos o de eliminación en caso de no estar obligados a conservarlos por imperativo legal o por razones legítimas de negocio. Nos reservamos el derecho a no tramitar aquellas solicitudes que sean improcedentes o vejatorias, que pongan en riesgo la privacidad de terceros, que resulten inviables o para las que la legislación local no exija derecho de acceso. Las solicitudes de acceso, rectificación o eliminación podrán enviarse a la dirección de nuestra sede social ende nuestra sede social en C/ Euclides, 16, 18100 Armilla (Granada) o en la cuenta de correo electrónico info@ingeniostelematicos.com\n',
    7: 'Páginas web y servicios de terceros \n\n Las aplicaciones pueden contener enlaces a páginas web, productos y servicios de terceros. También pueden utilizar u ofrecer productos o servicios de terceros. La recogida de datos por parte de terceros, introduciendo de datos sobre ubicaciones geográficas o datos de contacto, se guiará por sus respectivas políticas de privacidad. Le recomendamos consultar las políticas de privacidad de esos terceros.',
  },
};
/**
 * Stores the terms & conditions translations.
 */
const terms = {
  en: {
    title: 'Terms and conditions',
    1: 'Estos Términos y Condiciones de Uso regulan las reglas a que se sujeta la utilización de la APP/WEB cuYdo (en adelante, la APP/WEB) ofrecida por la empresa INGENIOS TELEMATICOS S.L. (en adelante INGENIOS TELEMATICOS). La descarga o utilización de la APP/WEB atribuye la condición de Usuario a quien lo haga e implica la aceptación de todas las condiciones incluidas en este documento y en la Política de Privacidad. El Usuario debería leer estas condiciones cada vez que utilice la APP/WEB, ya que podrían ser modificadas en lo sucesivo.',
    2: 'Únicamente los Usuarios expresamente autorizados por INGENIOS TELEMATICOS podrán acceder a la descarga y uso de la APP/WEB. Los Usuarios que no dispongan de autorización, no podrán acceder a dicho contenido.',
    3: 'Cargos: eres responsable del pago de todos los costes o gastos en los que incurras como resultado de descargar y usar la APP/WEB de INGENIOS TELEMATICOS, incluido cualquier cargo de red de operador o itinerancia. Consulta con tu proveedor de servicios los detalles al respecto.',
    4: 'Estadísticas anónimas: INGENIOS TELEMATICOS se reserva el derecho a realizar un seguimiento de tu actividad en la APP/WEB de y a informar de ello a nuestros proveedores de servicios estadísticos de terceros. Todo ello de forma anónima.',
    5: 'Protección de tu información personal: queremos ayudarte a llevar a cabo todos los pasos necesarios para proteger tu privacidad e información. Consulta la Política de privacidad de INGENIOS TELEMATICOS y los avisos sobre privacidad de la APP/WEB para conocer qué tipo de información recopilamos y las medidas que tomamos para proteger tu información personal.',
    6: 'Queda prohibido alterar o modificar ninguna parte de la APP/WEB a de los contenidas de la misma, eludir, desactivar o manipular de cualquier otra forma (o tratar de eludir, desactivar o manipular) las funciones de seguridad u otras funciones del programa y utilizar la APP/WEB o sus contenidos para un fin comercial o publicitario. Queda prohibido el uso de la APP/WEB con la finalidad de lesionar bienes, derechos o intereses de INGENIOS TELEMATICOS o de terceros. Queda igualmente prohibido realizar cualquier otro uso que altere, dañe o inutilice las redes, servidores, equipos, productos y programas informáticos de INGENIOS TELEMATICOS o de terceros.',
    7: 'La APP/WEB y sus contenidos (textos, fotografías, gráficos, imágenes, tecnología, software, links, contenidos, diseño gráfico, código fuente, etc.), así como las marcas y demás signos distintivos son propiedad de INGENIOS TELEMATICOS o de terceros, no adquiriendo el Usuario ningún derecho sobre ellos por el mero uso de la APP/WEB. El Usuario, deberá abstenerse de: a) Reproducir, copiar, distribuir, poner a disposición de terceros, comunicar públicamente, transformar o modificar la APP/WEB o sus contenidos, salvo en los casos contemplados en la ley o expresamente autorizados por INGENIOS TELEMATICOS o por el titular de dichos derechos. b) Reproducir o copiar para uso privado la APP/WEB o sus contenidos, así como comunicarlos públicamente o ponerlos a disposición de terceros cuando ello conlleve su reproducción. c) Extraer o reutilizar todo o parte sustancial de los contenidos integrantes de la APP/WEB.',
    8: 'Con sujeción a las condiciones establecidas en el apartado anterior, INGENIOS TELEMATICOS concede al Usuario una licencia de uso de la APP/WEB, no exclusiva, gratuita, para uso personal, circunscrita al territorio nacional y con carácter indefinido. Dicha licencia se concede también en los mismos términos con respecto a las actualizaciones y mejoras que se realizasen en la aplicación. Dichas licencias de uso podrán ser revocadas por INGENIOS TELEMATICOS unilateralmente en cualquier momento, mediante la mera notificación al Usuario.',
    9: 'Corresponde al Usuario, en todo caso, disponer de herramientas adecuadas para la detección y desinfección de programas maliciosos o cualquier otro elemento informático dañino. INGENIOS TELEMATICOS no se responsabiliza de los daños producidos a equipos informáticos durante el uso de la APP/WEB. Igualmente, INGENIOS TELEMATICOS no será responsable de los daños producidos a los Usuarios cuando dichos daños tengan su origen en fallos o desconexiones en las redes de telecomunicaciones que interrumpan el servicio.',
    10: 'IMPORTANTE: Podemos, sin que esto suponga ninguna obligación contigo, modificar estas Condiciones de uso sin avisar en cualquier momento. Si continúas utilizando la aplicación una vez realizada cualquier modificación en estas Condiciones de uso, esa utilización continuada constituirá la aceptación por tu parte de tales modificaciones. Si no aceptas estas condiciones de uso ni aceptas quedar sujeto a ellas, no debes utilizar la aplicación ni descargar o utilizar cualquier software relacionado. El uso que hagas de la aplicación queda bajo tu única responsabilidad. No tenemos responsabilidad alguna por la eliminación o la incapacidad de almacenar o trasmitir cualquier contenido u otra información mantenida o trasmitida por la aplicación. No somos responsables de la precisión o la fiabilidad de cualquier información o consejo trasmitidos a través de la aplicación. Podemos, en cualquier momento, limitar o interrumpir tu uso a nuestra única discreción. Hasta el máximo que permite la ley, en ningún caso seremos responsables por cualquier pérdida o daño relacionados.',
    11: 'El Usuario se compromete a hacer un uso correcto de la APP/WEB, de conformidad con la Ley, con los presentes Términos y Condiciones de Uso y con las demás reglamentos e instrucciones que, en su caso, pudieran ser de aplicación El Usuario responderá frente a INGENIOS TELEMATICOS y frente a terceros de cualesquiera daños o perjuicios que pudieran causarse por incumplimiento de estas obligaciones.',
    12: 'Estos Términos y Condiciones de Uso se rigen íntegramente por la legislación española. Para la resolución de cualquier conflicto relativo a su interpretación o aplicación, el Usuario se somete expresamente a la jurisdicción de los tribunales de Granada (España).',
  },
  es: {
    title: 'Términos y condiciones',
    1: 'Estos Términos y Condiciones de Uso regulan las reglas a que se sujeta la utilización de la APP/WEB cuYdo (en adelante, la APP/WEB) ofrecida por la empresa INGENIOS TELEMATICOS S.L. (en adelante INGENIOS TELEMATICOS). La descarga o utilización de la APP/WEB atribuye la condición de Usuario a quien lo haga e implica la aceptación de todas las condiciones incluidas en este documento y en la Política de Privacidad. El Usuario debería leer estas condiciones cada vez que utilice la APP/WEB, ya que podrían ser modificadas en lo sucesivo.',
    2: 'Únicamente los Usuarios expresamente autorizados por INGENIOS TELEMATICOS podrán acceder a la descarga y uso de la APP/WEB. Los Usuarios que no dispongan de autorización, no podrán acceder a dicho contenido.',
    3: 'Cargos: eres responsable del pago de todos los costes o gastos en los que incurras como resultado de descargar y usar la APP/WEB de INGENIOS TELEMATICOS, incluido cualquier cargo de red de operador o itinerancia. Consulta con tu proveedor de servicios los detalles al respecto.',
    4: 'Estadísticas anónimas: INGENIOS TELEMATICOS se reserva el derecho a realizar un seguimiento de tu actividad en la APP/WEB de y a informar de ello a nuestros proveedores de servicios estadísticos de terceros. Todo ello de forma anónima.',
    5: 'Protección de tu información personal: queremos ayudarte a llevar a cabo todos los pasos necesarios para proteger tu privacidad e información. Consulta la Política de privacidad de INGENIOS TELEMATICOS y los avisos sobre privacidad de la APP/WEB para conocer qué tipo de información recopilamos y las medidas que tomamos para proteger tu información personal.',
    6: 'Queda prohibido alterar o modificar ninguna parte de la APP/WEB a de los contenidas de la misma, eludir, desactivar o manipular de cualquier otra forma (o tratar de eludir, desactivar o manipular) las funciones de seguridad u otras funciones del programa y utilizar la APP/WEB o sus contenidos para un fin comercial o publicitario. Queda prohibido el uso de la APP/WEB con la finalidad de lesionar bienes, derechos o intereses de INGENIOS TELEMATICOS o de terceros. Queda igualmente prohibido realizar cualquier otro uso que altere, dañe o inutilice las redes, servidores, equipos, productos y programas informáticos de INGENIOS TELEMATICOS o de terceros.',
    7: 'La APP/WEB y sus contenidos (textos, fotografías, gráficos, imágenes, tecnología, software, links, contenidos, diseño gráfico, código fuente, etc.), así como las marcas y demás signos distintivos son propiedad de INGENIOS TELEMATICOS o de terceros, no adquiriendo el Usuario ningún derecho sobre ellos por el mero uso de la APP/WEB. El Usuario, deberá abstenerse de: a) Reproducir, copiar, distribuir, poner a disposición de terceros, comunicar públicamente, transformar o modificar la APP/WEB o sus contenidos, salvo en los casos contemplados en la ley o expresamente autorizados por INGENIOS TELEMATICOS o por el titular de dichos derechos. b) Reproducir o copiar para uso privado la APP/WEB o sus contenidos, así como comunicarlos públicamente o ponerlos a disposición de terceros cuando ello conlleve su reproducción. c) Extraer o reutilizar todo o parte sustancial de los contenidos integrantes de la APP/WEB.',
    8: 'Con sujeción a las condiciones establecidas en el apartado anterior, INGENIOS TELEMATICOS concede al Usuario una licencia de uso de la APP/WEB, no exclusiva, gratuita, para uso personal, circunscrita al territorio nacional y con carácter indefinido. Dicha licencia se concede también en los mismos términos con respecto a las actualizaciones y mejoras que se realizasen en la aplicación. Dichas licencias de uso podrán ser revocadas por INGENIOS TELEMATICOS unilateralmente en cualquier momento, mediante la mera notificación al Usuario.',
    9: 'Corresponde al Usuario, en todo caso, disponer de herramientas adecuadas para la detección y desinfección de programas maliciosos o cualquier otro elemento informático dañino. INGENIOS TELEMATICOS no se responsabiliza de los daños producidos a equipos informáticos durante el uso de la APP/WEB. Igualmente, INGENIOS TELEMATICOS no será responsable de los daños producidos a los Usuarios cuando dichos daños tengan su origen en fallos o desconexiones en las redes de telecomunicaciones que interrumpan el servicio.',
    10: 'IMPORTANTE: Podemos, sin que esto suponga ninguna obligación contigo, modificar estas Condiciones de uso sin avisar en cualquier momento. Si continúas utilizando la aplicación una vez realizada cualquier modificación en estas Condiciones de uso, esa utilización continuada constituirá la aceptación por tu parte de tales modificaciones. Si no aceptas estas condiciones de uso ni aceptas quedar sujeto a ellas, no debes utilizar la aplicación ni descargar o utilizar cualquier software relacionado. El uso que hagas de la aplicación queda bajo tu única responsabilidad. No tenemos responsabilidad alguna por la eliminación o la incapacidad de almacenar o trasmitir cualquier contenido u otra información mantenida o trasmitida por la aplicación. No somos responsables de la precisión o la fiabilidad de cualquier información o consejo trasmitidos a través de la aplicación. Podemos, en cualquier momento, limitar o interrumpir tu uso a nuestra única discreción. Hasta el máximo que permite la ley, en ningún caso seremos responsables por cualquier pérdida o daño relacionados.',
    11: 'El Usuario se compromete a hacer un uso correcto de la APP/WEB, de conformidad con la Ley, con los presentes Términos y Condiciones de Uso y con las demás reglamentos e instrucciones que, en su caso, pudieran ser de aplicación El Usuario responderá frente a INGENIOS TELEMATICOS y frente a terceros de cualesquiera daños o perjuicios que pudieran causarse por incumplimiento de estas obligaciones.',
    12: 'Estos Términos y Condiciones de Uso se rigen íntegramente por la legislación española. Para la resolución de cualquier conflicto relativo a su interpretación o aplicación, el Usuario se somete expresamente a la jurisdicción de los tribunales de Granada (España).',
  },
};

export {privacy, terms};
